### ISSUE TITLE
Weird convergence on nutrients at 2100

### ISSUE THREAD

**Issue by sarahbridle** [jucordero/FoF_Dashboard_MVP#3]
<img width="239" alt="2022-03-29 18 42 51" src="https://user-images.githubusercontent.com/1469976/160672871-74b410b6-0ef8-4b2c-ac5a-c5142b00e706.png">
looks a bit weird?

**Comment by jucordero** [comment]
Pushed a fix for this.
The issue was that nutrients were also being scaled up by population growth, instead of fixing then to the 2019 values.
