### ISSUE TITLE
Confusing slider / button situation 'Reduce ruminant..' / 'Meat-free days..'

### ISSUE THREAD

**Issue by sarahbridle** [jucordero/FoF_Dashboard_MVP#4]
Not sure if this is a bug or just a bit confusing:

The 'Reduce ruminant meat consumption' slider only works if the 'Meat free days' button is checked (and not if the 'Type of vegetarian diet button is checked).

Whereas I think it should work irrespective of these buttons? Or am I missing something?

**Comment by jucordero** [comment]
It is a bug. I'll adjust this now to work with both checkboxes.

**Comment by jucordero** [comment]
Just pushed a fix
